# delelopment
system:
  # 设定模式(debug/release/test,正式版改为release)
  mode: debug
  # url前缀
  url-path-prefix: api
  # 程序监听端口
  port: 8080
  # 是否初始化数据(没有初始数据时使用, 已发布正式版改为false)
  init-data: false

logs:
  # 日志等级(-1:Debug, 0:Info, 1:Warn, 2:Error, 3:DPanic, 4:Panic, 5:Fatal, -1<=level<=5, 参照zap.level源码)
  level: -1
  # 日志路径
  path: logs
  # 文件最大大小, M
  max-size: 50
  # 备份数
  max-backups: 10
  # 存放时间, 天
  max-age: 7
  # 是否压缩
  compress: false

# 令牌桶限流配置
rate-limit:
  # 填充一个令牌需要的时间间隔,毫秒
  fill-interval: 50
  # 桶容量
  capacity: 200

# 飞书配置
feiShu:
  # 运维审批群群ID
  chat-id: oc_xxxxxxxxxxxxxxxxxxxxxxxxxxxx
  # 飞书应用信息
  app-id: cli_xxxxxxxxxxxxxxx
  app-secret: xxxxxxxxxxxxxxxx

aliYun:
  # 云 ak/sk
  ak: xxxxxxxxxxxxxxxxxxxxxx
  sk: xxxxxxxxxxxxxxxxxxxxxxxxxxx
  # 
  region: cn-hangzhou
  # 主账号id
  uid: 111111111111111

redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  db: 0
  pool-size: 20